export const GET_ALL_CUSTOMERS_REQUEST = 'GET_ALL_CUSTOMERS_REQUEST'
export const GET_ALL_CUSTOMERS_SUCCESS = 'GET_ALL_CUSTOMERS_SUCCESS'
export const GET_ALL_CUSTOMERS_ERRORS = 'GET_ALL_CUSTOMERS_ERRORS'

export const GET_ALL_OPTIONS_CUSTOMERS_REQUEST = 'GET_ALL_OPTIONS_CUSTOMERS_REQUEST'
export const GET_ALL_OPTIONS_CUSTOMERS_SUCCESS = 'GET_ALL_OPTIONS_CUSTOMERS_SUCCESS'
export const GET_ALL_OPTIONS_CUSTOMERS_ERRORS = 'GET_ALL_OPTIONS_CUSTOMERS_ERRORS'

export const CREATE_CUSTOMER_REQUEST = 'CREATE_CUSTOMER_REQUEST'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_ERRORS = 'CREATE_CUSTOMER_ERRORS'

export const RETRIEVE_CUSTOMER_REQUEST = 'RETRIEVE_CUSTOMER_REQUEST'
export const RETRIEVE_CUSTOMER_SUCCESS = 'RETRIEVE_CUSTOMER_SUCCESS'
export const RETRIEVE_CUSTOMER_ERRORS = 'RETRIEVE_CUSTOMER_ERRORS'

export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_ERRORS = 'UPDATE_CUSTOMER_ERRORS'

export const DESTROY_CUSTOMER_REQUEST = 'DESTROY_CUSTOMER_REQUEST'
export const DESTROY_CUSTOMER_SUCCESS = 'DESTROY_CUSTOMER_SUCCESS'
export const DESTROY_CUSTOMER_ERRORS = 'DESTROY_CUSTOMER_ERRORS'
