export const GET_ALL_ACTIVITY_TYPES_REQUEST = 'GET_ALL_ACTIVITY_TYPES_REQUEST'
export const GET_ALL_ACTIVITY_TYPES_SUCCESS = 'GET_ALL_ACTIVITY_TYPES_SUCCESS'
export const GET_ALL_ACTIVITY_TYPES_ERRORS = 'GET_ALL_ACTIVITY_TYPES_ERRORS'

export const GET_ALL_OPTIONS_ACTIVITY_TYPES_REQUEST = 'GET_ALL_OPTIONS_ACTIVITY_TYPES_REQUEST'
export const GET_ALL_OPTIONS_ACTIVITY_TYPES_SUCCESS = 'GET_ALL_OPTIONS_ACTIVITY_TYPES_SUCCESS'
export const GET_ALL_OPTIONS_ACTIVITY_TYPES_ERRORS = 'GET_ALL_OPTIONS_ACTIVITY_TYPES_ERRORS'

export const CREATE_ACTIVITY_TYPE_REQUEST = 'CREATE_ACTIVITY_TYPE_REQUEST'
export const CREATE_ACTIVITY_TYPE_SUCCESS = 'CREATE_ACTIVITY_TYPE_SUCCESS'
export const CREATE_ACTIVITY_TYPE_ERRORS = 'CREATE_ACTIVITY_TYPE_ERRORS'

export const RETRIEVE_ACTIVITY_TYPE_REQUEST = 'RETRIEVE_ACTIVITY_TYPE_REQUEST'
export const RETRIEVE_ACTIVITY_TYPE_SUCCESS = 'RETRIEVE_ACTIVITY_TYPE_SUCCESS'
export const RETRIEVE_ACTIVITY_TYPE_ERRORS = 'RETRIEVE_ACTIVITY_TYPE_ERRORS'

export const UPDATE_ACTIVITY_TYPE_REQUEST = 'UPDATE_ACTIVITY_TYPE_REQUEST'
export const UPDATE_ACTIVITY_TYPE_SUCCESS = 'UPDATE_ACTIVITY_TYPE_SUCCESS'
export const UPDATE_ACTIVITY_TYPE_ERRORS = 'UPDATE_ACTIVITY_TYPE_ERRORS'

export const DESTROY_ACTIVITY_TYPE_REQUEST = 'DESTROY_ACTIVITY_TYPE_REQUEST'
export const DESTROY_ACTIVITY_TYPE_SUCCESS = 'DESTROY_ACTIVITY_TYPE_SUCCESS'
export const DESTROY_ACTIVITY_TYPE_ERRORS = 'DESTROY_ACTIVITY_TYPE_ERRORS'
