export const GET_ALL_ACTIVITIES_REQUEST = 'GET_ALL_ACTIVITIES_REQUEST'
export const GET_ALL_ACTIVITIES_SUCCESS = 'GET_ALL_ACTIVITIES_SUCCESS'
export const GET_ALL_ACTIVITIES_ERRORS = 'GET_ALL_ACTIVITIES_ERRORS'

export const GET_ALL_OPTIONS_ACTIVITIES_REQUEST = 'GET_ALL_OPTIONS_ACTIVITIES_REQUEST'
export const GET_ALL_OPTIONS_ACTIVITIES_SUCCESS = 'GET_ALL_OPTIONS_ACTIVITIES_SUCCESS'
export const GET_ALL_OPTIONS_ACTIVITIES_ERRORS = 'GET_ALL_OPTIONS_ACTIVITIES_ERRORS'

export const CREATE_ACTIVITY_REQUEST = 'CREATE_ACTIVITY_REQUEST'
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS'
export const CREATE_ACTIVITY_ERRORS = 'CREATE_ACTIVITY_ERRORS'

export const RETRIEVE_ACTIVITY_REQUEST = 'RETRIEVE_ACTIVITY_REQUEST'
export const RETRIEVE_ACTIVITY_SUCCESS = 'RETRIEVE_ACTIVITY_SUCCESS'
export const RETRIEVE_ACTIVITY_ERRORS = 'RETRIEVE_ACTIVITY_ERRORS'

export const UPDATE_ACTIVITY_REQUEST = 'UPDATE_ACTIVITY_REQUEST'
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS'
export const UPDATE_ACTIVITY_ERRORS = 'UPDATE_ACTIVITY_ERRORS'

export const DESTROY_ACTIVITY_REQUEST = 'DESTROY_ACTIVITY_REQUEST'
export const DESTROY_ACTIVITY_SUCCESS = 'DESTROY_ACTIVITY_SUCCESS'
export const DESTROY_ACTIVITY_ERRORS = 'DESTROY_ACTIVITY_ERRORS'
