export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_ERRORS = 'GET_ALL_USERS_ERRORS'

export const GET_ALL_OPTIONS_USERS_REQUEST = 'GET_ALL_OPTIONS_USERS_REQUEST'
export const GET_ALL_OPTIONS_USERS_SUCCESS = 'GET_ALL_OPTIONS_USERS_SUCCESS'
export const GET_ALL_OPTIONS_USERS_ERRORS = 'GET_ALL_OPTIONS_USERS_ERRORS'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_ERRORS = 'CREATE_USER_ERRORS'

export const RETRIEVE_USER_REQUEST = 'RETRIEVE_USER_REQUEST'
export const RETRIEVE_USER_SUCCESS = 'RETRIEVE_USER_SUCCESS'
export const RETRIEVE_USER_ERRORS = 'RETRIEVE_USER_ERRORS'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERRORS = 'UPDATE_USER_ERRORS'

export const DESTROY_USER_REQUEST = 'DESTROY_USER_REQUEST'
export const DESTROY_USER_SUCCESS = 'DESTROY_USER_SUCCESS'
export const DESTROY_USER_ERRORS = 'DESTROY_USER_ERRORS'
